-   id: ufonormalizer
    name: ufoNormalizer
    description: Format UFOs with ufoNormalizer.
    entry: ufo-normalizer
    language: python
    types: [file]
    files: .ufo/
    stages: [pre-commit, manual]
    pass_filenames: false
    require_serial: true
